# Generated by Django 5.0.7 on 2024-10-22 13:30

import app.common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthUserModel",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "first_name",
                    models.CharField(
                        max_length=125,
                        validators=[
                            app.common.validators.AuthValidators.validate_first_name
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=120,
                        validators=[
                            app.common.validators.AuthValidators.validate_last_name
                        ],
                    ),
                ),
                ("username", models.CharField(max_length=120, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now_add=True)),
                ("country", models.CharField(default="Nigeria", max_length=230)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "Users",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sponsors",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp", models.CharField(max_length=12)),
                ("otp_created", models.DateField(auto_now_add=True)),
                ("username", models.CharField(max_length=120, unique=True)),
                ("is_authenticated", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "Sponsors",
            },
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("image", models.ImageField(upload_to="images")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "User Images",
            },
        ),
        migrations.CreateModel(
            name="ProductList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("image", models.ImageField(upload_to="product_images")),
                (
                    "confirmation_massage",
                    models.TextField(default="Product ordered !!!"),
                ),
                ("setting", models.JSONField(default=dict)),
                ("draft", models.BooleanField(default=False)),
                (
                    "category",
                    models.ManyToManyField(related_name="products", to="app.category"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Product",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("object_id", models.UUIDField(null=True)),
                ("verified", models.BooleanField(default=False)),
                ("_type", models.CharField(max_length=120)),
                ("amount", models.FloatField()),
                ("message", models.TextField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="app.sponsors",
                    ),
                ),
            ],
            options={
                "db_table": "User Payment",
            },
        ),
        migrations.CreateModel(
            name="Followership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="app.sponsors",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserGalary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("title", models.CharField(max_length=120)),
                ("exclusive", models.BooleanField(default=False)),
                ("description", models.TextField()),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="user_galaries", to="app.images"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_galaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "User Galary",
            },
        ),
        migrations.CreateModel(
            name="UserMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("name", models.CharField(max_length=225)),
                ("image", models.ImageField(null=True, upload_to="memberships_images")),
                ("rewards", models.JSONField(default=list)),
                ("welcome_note", models.TextField(null=True)),
                ("description", models.TextField()),
                ("price_per_month", models.FloatField()),
                ("price_per_year", models.FloatField(null=True)),
                ("full_time", models.BooleanField(default=False)),
                ("max_members", models.IntegerField(default=1000, null=True)),
                ("limit_members", models.BooleanField(default=False)),
                ("full_price", models.IntegerField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "User Membership !",
            },
        ),
        migrations.CreateModel(
            name="UserMembers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("yearly", models.BooleanField(default=False)),
                ("date_due", models.DateTimeField(blank=True, null=True)),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberhips",
                        to="app.sponsors",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membershiPlan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsor_members",
                        to="app.usermembership",
                    ),
                ),
            ],
            options={
                "db_table": "User  Members",
            },
        ),
        migrations.CreateModel(
            name="UserPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("title", models.CharField(max_length=250)),
                ("body", models.TextField()),
                ("scheduled", models.BooleanField(default=False)),
                (
                    "scheduled_for",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("draft", models.BooleanField(default=False)),
                ("exlusive", models.BooleanField(default=False)),
                (
                    "images",
                    models.ManyToManyField(related_name="get_post", to="app.images"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_post",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "User Post",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("bio", models.TextField()),
                ("interests", models.JSONField(default=list, null=True)),
                (
                    "profile_image",
                    models.ImageField(null=True, upload_to="user_profile"),
                ),
                ("cover_image", models.ImageField(null=True, upload_to="cover_images")),
                ("socials", models.JSONField(default=dict, null=True)),
                ("paymentDetails", models.JSONField(default=dict, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "User Profile",
            },
        ),
    ]
