# Generated by Django 5.0.7 on 2024-10-03 10:13

import app.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthUserModel",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "first_name",
                    models.CharField(
                        max_length=125,
                        validators=[
                            app.common.validators.AuthValidators.validate_first_name
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=120,
                        validators=[
                            app.common.validators.AuthValidators.validate_last_name
                        ],
                    ),
                ),
                ("username", models.CharField(max_length=120, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now_add=True)),
                ("country", models.CharField(default="Nigeria", max_length=230)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "Users",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductList",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("image", models.ImageField(upload_to="product_images")),
                (
                    "confirmation_massage",
                    models.TextField(default="Product ordered !!!"),
                ),
                ("setting", models.JSONField(default=dict)),
                ("draft", models.BooleanField(default=False)),
                (
                    "category",
                    models.ManyToManyField(related_name="products", to="app.category"),
                ),
            ],
            options={
                "db_table": "Products",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("bio", models.TextField()),
                ("interests", models.JSONField(default=list, null=True)),
                (
                    "profile_image",
                    models.ImageField(null=True, upload_to="user_profile"),
                ),
                ("cover_image", models.ImageField(null=True, upload_to="cover_images")),
                ("socials", models.JSONField(default=list, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "User Profile",
            },
        ),
    ]
