# Generated by Django 5.0.7 on 2024-10-01 21:53

import app.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_authusermodel_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cover_image",
            field=models.ImageField(null=True, upload_to="cover_images"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(null=True, upload_to="user_profile"),
        ),
        migrations.AlterField(
            model_name="authusermodel",
            name="first_name",
            field=models.CharField(
                max_length=125,
                validators=[app.common.validators.AuthValidators.validate_first_name],
            ),
        ),
        migrations.AlterField(
            model_name="authusermodel",
            name="last_name",
            field=models.CharField(
                max_length=120,
                validators=[app.common.validators.AuthValidators.validate_last_name],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="inetrests",
            field=models.JSONField(default=list, null=True),
        ),
    ]
