# Generated by Django 5.0.7 on 2024-10-03 19:31

import app.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_uuid_category_id_rename_uuid_productlist_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productlist",
            options={"ordering": ["date_created"]},
        ),
        migrations.AlterField(
            model_name="authusermodel",
            name="first_name",
            field=models.CharField(
                max_length=125,
                validators=[app.common.validators.AuthValidators.validate_first_name],
            ),
        ),
        migrations.AlterField(
            model_name="authusermodel",
            name="last_name",
            field=models.CharField(
                max_length=120,
                validators=[app.common.validators.AuthValidators.validate_last_name],
            ),
        ),
        migrations.AlterModelTable(
            name="productlist",
            table="Product",
        ),
    ]
