# Generated by Django 5.0.7 on 2024-10-01 22:11

import app.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_userprofile_cover_image_userprofile_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="socials",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="authusermodel",
            name="first_name",
            field=models.CharField(
                max_length=125,
                validators=[app.common.validators.AuthValidators.validate_first_name],
            ),
        ),
        migrations.AlterField(
            model_name="authusermodel",
            name="last_name",
            field=models.CharField(
                max_length=120,
                validators=[app.common.validators.AuthValidators.validate_last_name],
            ),
        ),
    ]
