# Generated by Django 5.0.7 on 2024-10-05 11:40

import app.common.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_productlist_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpost",
            name="draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpost",
            name="exlusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpost",
            name="scheduled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpost",
            name="scheduled_for",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="authusermodel",
            name="first_name",
            field=models.CharField(
                max_length=125,
                validators=[app.common.validators.AuthValidators.validate_first_name],
            ),
        ),
        migrations.AlterField(
            model_name="authusermodel",
            name="last_name",
            field=models.CharField(
                max_length=120,
                validators=[app.common.validators.AuthValidators.validate_last_name],
            ),
        ),
    ]
