# Generated by Django 5.0.7 on 2024-10-09 10:47

import app.common.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_userprofile_paymentdetails_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("name", models.CharField(max_length=225)),
                ("image", models.ImageField(null=True, upload_to="memberships_images")),
                ("rewards", models.JSONField(default=list)),
                ("welcome_note", models.TextField(null=True)),
                ("description", models.TextField()),
                ("price_per_month", models.FloatField()),
                ("price_per_year", models.FloatField(null=True)),
                ("full_time", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="authusermodel",
            name="first_name",
            field=models.CharField(
                max_length=125,
                validators=[app.common.validators.AuthValidators.validate_first_name],
            ),
        ),
        migrations.AlterField(
            model_name="authusermodel",
            name="last_name",
            field=models.CharField(
                max_length=120,
                validators=[app.common.validators.AuthValidators.validate_last_name],
            ),
        ),
    ]
