# Generated by Django 5.0.7 on 2024-10-10 21:59

import app.common.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_authusermodel_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsors",
            fields=[
                ("otp_created", models.DateField(auto_created=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp", models.CharField(max_length=12)),
            ],
            options={
                "db_table": "Sponsors",
            },
        ),
        migrations.AlterField(
            model_name="authusermodel",
            name="first_name",
            field=models.CharField(
                max_length=125,
                validators=[app.common.validators.AuthValidators.validate_first_name],
            ),
        ),
        migrations.AlterField(
            model_name="authusermodel",
            name="last_name",
            field=models.CharField(
                max_length=120,
                validators=[app.common.validators.AuthValidators.validate_last_name],
            ),
        ),
    ]
